name: "Run Super-Linter"

on: ["push", "pull_request"]
permissions: read-all

jobs:
  lint:
    name: Super-Lint
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: read
      statuses: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          # super-linter needs the full git history to get the
          # list of files that changed across commits
          fetch-depth: 0

      - name: Superlinter
        uses: super-linter/super-linter@v7.2.1
        env:
          DEFAULT_BRANCH: main
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          FILTER_REGEX_EXCLUDE: (.*test/bats/.*|.*.bats|.*dist.*)
          VALIDATE_JSCPD: false
          VALIDATE_YAML: false
          BASH_EXEC_IGNORE_LIBRARIES: true
